# Makefile for the Huawei Kernel Harden.
#

obj-$(CONFIG_HUAWEI_HIDESYMS) += kernel_harden/hw_litehide_symbols.o
obj-$(CONFIG_GCC_PLUGIN_RANDSTRUCT_DEBUGFS) += kernel_harden/hw_struct_rand_debugfs.o
obj-y += kernel_harden/hw_ptrace_log.o

